version="0.3.2"

[scripts]
## Builds Tailwind CSS for development (no purging)
build-tailwind-dev = [
    "npm install -D tailwindcss",
    "npm install -D @tailwindcss/typography",
    "npx tailwindcss -i ./src/global.css -c ./tailwind.config.js -o ./tailwind.css"
]
## Builds Tailwind CSS for production (maximum purging and minification)
build-tailwind-prod = [
    "NODE_ENV=production npx tailwindcss -i ./src/global.css -c ./tailwind.config.js -o ./tailwind.css --minify"
]

build-html-prod = [
    
]

## bonnie build dev
build.subcommands.dev = [
    "bonnie build-tailwind-dev",
]
## bonnie run dev
run.subcommands.dev = [
    "bonnie build dev",
    "RUSTFLAGS=--cfg=web_sys_unstable_apis trunk serve"
]

## bonnie build release
build.subcommands.release = [
    "bonnie build-tailwind-prod",
    "RUSTFLAGS=--cfg=web_sys_unstable_apis trunk build --release=true --public-url=\"/pages/iwollmann/changelog-builder/\""
]